"""Human-in-the-Loop Approval models."""

import hashlib
import json
from typing import Dict, Any, Optional
from datetime import datetime, timedelta
import uuid
from pydantic import BaseModel, Field
from .enums import ApprovalStatus, ActionType


def compute_parameter_hash(parameters: Dict[str, Any]) -> str:
    """Compute deterministic hash of action parameters to enforce binding."""
    # Convert parameters to sorted JSON string
    serialized = json.dumps(parameters, sort_keys=True, default=str)
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()[:16]


class ApprovalRequest(BaseModel):
    """Request generated by the agent requiring human authorization."""
    request_id: str
    user_identity: str
    action_type: ActionType
    parameters: Dict[str, Any]
    description: str
    risk_level: str = "medium"  # "low", "medium", "high", "consequential"
    validity_minutes: int = 60


class ApprovalRecord(BaseModel):
    """Enforceable approval record binding user authorization to parameters."""
    approval_id: str = Field(default_factory=lambda: f"appr_{uuid.uuid4().hex[:10]}")
    request_id: str
    user_identity: str
    action_being_approved: ActionType
    relevant_parameters: Dict[str, Any]
    parameter_hash: str
    approval_status: ApprovalStatus = ApprovalStatus.PENDING
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    expiration: datetime = Field(
        default_factory=lambda: datetime.utcnow() + timedelta(hours=1)
    )
    granted_by: Optional[str] = None
    granted_at: Optional[datetime] = None
    rejection_reason: Optional[str] = None
    is_simulation: bool = False

    @classmethod
    def create_pending(
        cls,
        request_id: str,
        user_identity: str,
        action_type: ActionType,
        parameters: Dict[str, Any],
        validity_minutes: int = 60,
        is_simulation: bool = False,
    ) -> "ApprovalRecord":
        return cls(
            request_id=request_id,
            user_identity=user_identity,
            action_being_approved=action_type,
            relevant_parameters=parameters,
            parameter_hash=compute_parameter_hash(parameters),
            approval_status=ApprovalStatus.PENDING,
            timestamp=datetime.utcnow(),
            expiration=datetime.utcnow() + timedelta(minutes=validity_minutes),
            is_simulation=is_simulation,
        )

    def is_valid_for(self, action_type: ActionType, parameters: Dict[str, Any]) -> bool:
        """Check if this approval is active and matches the exact parameters."""
        if self.approval_status != ApprovalStatus.GRANTED:
            return False
        if datetime.utcnow() > self.expiration:
            return False
        if self.action_being_approved != action_type:
            return False
        current_hash = compute_parameter_hash(parameters)
        return current_hash == self.parameter_hash
